name: uk-pep-scraper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flask=2.3.3
  - numpy>=1.21.0,<2.0
  - pandas>=1.3.0
  - requests>=2.25.0
  - gunicorn=21.2.0
  # Testing dependencies
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - pytest-mock>=3.10.0
  - pytest-timeout>=2.1.0
  - pytest-html>=3.1.0
  - pytest-xdist>=3.0.0
  - coverage>=7.0.0
  - pip
  - pip:
      - pdpy==0.1.6
      - pytest-json-report>=1.5.0
      - pytest-benchmark>=4.0.0
      - debugpy>=1.8.0  # VS Code debugging support
      - pytest-json>=0.4.0  # Additional test reporting
