name: uk-pep-scraper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flask=2.3.3
  - numpy>=1.21.0,<2.0
  - pandas>=1.3.0
  - requests>=2.25.0
  - gunicorn=21.2.0
  - pip
  - pip:
    - pdpy==0.1.6
